name       : sdl1-sound
version    : 1.0.3
release    : 2
source     :
    - http://icculus.org/SDL_sound/downloads/SDL_sound-1.0.3.tar.gz : 3999fd0bbb485289a52be14b2f68b571cb84e380cc43387eadf778f64c79e6df
license    : LGPL-2.1
component  : multimedia.library
summary    : Library that handles the decoding of several popular sound file formats,
    such as .WAV and .MP3.
description: |
    Library that handles the decoding of several popular sound file formats, such as .WAV and .MP3.
emul32     : yes
builddeps  :
    - pkgconfig32(flac)
    - pkgconfig32(libmodplug)
    - pkgconfig32(libmpg123)
    - pkgconfig32(sdl)
    - pkgconfig32(speex)
    - pkgconfig32(vorbis)
    - pkgconfig32(wavpack)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
